# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f93bc6b0b5bba1ff179b10e6087c47d556ff732e2ea6a40a0d26e5504e46141e1ff802f0fb8cc034b742b98488938522b3470de3c809e9a0309cf6482dfd5f4

test:
  secret_key_base: a3027ffdea8e4f11986368f4b36f84f87afc7cae37454f83bbaacacf2da997681d55d845e8b9cee32695d51286e48e2fab5bb2fc041a32c5bd5d3dd6be2c4dff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
